# Generated by Django 4.2.1 on 2023-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sender", models.CharField(max_length=100)),
                ("Reciever", models.CharField(max_length=100)),
                ("Amount", models.IntegerField()),
                ("Date_time", models.DateTimeField()),
                ("Reference_Number", models.CharField(max_length=20)),
                ("Payment_Status", models.CharField(max_length=20)),
            ],
        ),
    ]
