# Generated by Django 4.2.1 on 2023-06-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0002_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="MESSAGES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("From", models.CharField(max_length=100)),
                ("To", models.CharField(max_length=100)),
                ("Message", models.IntegerField()),
                ("Date_time", models.DateTimeField()),
            ],
        ),
    ]
