# Generated by Django 4.2.1 on 2023-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0003_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="Message",
            field=models.CharField(max_length=300),
        ),
    ]
