# Generated by Django 4.2.1 on 2023-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0004_alter_messages_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("From", models.CharField(max_length=100)),
                ("Query", models.TextField()),
                ("Date_time", models.DateTimeField()),
                ("Query_Status", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="messages", name="Message", field=models.TextField(),
        ),
    ]
