# Generated by Django 4.2.1 on 2023-06-15 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0005_queries_alter_messages_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="Remarks",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
