# Generated by Django 4.2.1 on 2023-06-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0006_payments_remarks"),
    ]

    operations = [
        migrations.AlterModelTable(name="users", table="users",),
    ]
