# Generated by Django 4.2.1 on 2023-06-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0007_alter_users_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="users", table=None,),
    ]
