# Generated by Django 4.2.1 on 2023-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0008_alter_users_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="Unique_Key",
            field=models.CharField(default="qwertyuiopasd", max_length=13),
        ),
    ]
