# Generated by Django 4.2.1 on 2023-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0009_users_unique_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="Active_Status",
            field=models.BooleanField(default=False),
        ),
    ]
